const fs = require('node:fs');
const path = require('node:path');
const test = require('node:test');
const assert = require('node:assert/strict');

const root = path.join(__dirname, '..');
const preload = fs.readFileSync(path.join(root, 'electron', 'preload.cjs'), 'utf8');
const main = fs.readFileSync(path.join(root, 'electron', 'main.cjs'), 'utf8');
const renderer = fs.readFileSync(path.join(root, 'renderer', 'index.html'), 'utf8');
const rendererScript = fs.readFileSync(path.join(root, 'renderer', 'app.js'), 'utf8');

test('Studio exposes account login instead of API-key configuration', () => {
  assert.match(preload, /loadImagePreviews:/);
  assert.match(main, /studio:load-image-previews/);
  assert.match(main, /WSL_IMAGE_ROOTS/);
  assert.match(main, /readlink -f/);
  assert.match(rendererScript, /extractImagePaths/);
  assert.match(rendererScript, /appendImagePreviews/);
  assert.match(rendererScript, /MEDIA:/);
  assert.match(preload, /login:/);
  assert.match(preload, /register:/);
  assert.match(preload, /logout:/);
  assert.doesNotMatch(preload, /saveConnection/);
  assert.match(main, /safeStorage\.encryptString/);
  assert.match(main, /Menu\.setApplicationMenu\(null\)/);
  assert.match(main, /accountBaseUrl/);
  assert.doesNotMatch(renderer, /id="api-key"/);
  assert.match(renderer, /连接账号/);
  assert.match(renderer, /<button type="button" class="icon-button" id="cancel-account"/);
  assert.match(renderer, /<button type="button" class="secondary-button" id="cancel-account-action"/);
  assert.match(renderer, /id="account-error"[^>]*role="alert"/);
  assert.match(renderer, /id="skin-toggle"/);
  assert.match(renderer, /id="skin-name"/);
  assert.match(renderer, /id="skin-settings"/);
  assert.match(renderer, /id="skin-dialog"/);
  assert.match(renderer, /id="skin-position-x"/);
  assert.match(renderer, /id="choose-skin-sidebar"/);
  assert.match(renderer, /id="choose-skin-composer"/);
  assert.match(renderer, /id="skin-sidebar-text-color"/);
  assert.match(renderer, /id="skin-composer-text-color"/);
  assert.match(renderer, /id="skin-text-scale"/);
  assert.match(renderer, /id="skin-sidebar-text-scale"/);
  assert.match(renderer, /id="skin-composer-text-scale"/);
  assert.match(fs.readFileSync(path.join(root, 'renderer', 'app.js'), 'utf8'), /addPrecisionInputs/);
  assert.match(fs.readFileSync(path.join(root, 'renderer', 'app.js'), 'utf8'), /hexOverlay/);
  assert.match(fs.readFileSync(path.join(root, 'renderer', 'styles.css'), 'utf8'), /composer \.attach-button/);
  assert.match(fs.readFileSync(path.join(root, 'renderer', 'styles.css'), 'utf8'), /message-body[^}]*var\(--app-ink\)/);
  assert.match(fs.readFileSync(path.join(root, 'renderer', 'app.js'), 'utf8'), /message-avatar/);
  assert.ok(fs.existsSync(path.join(root, 'renderer', 'assets', 'husband-avatar.png')));
  assert.ok(fs.existsSync(path.join(root, 'renderer', 'assets', 'anjie-avatar.png')));
  assert.match(fs.readFileSync(path.join(root, 'renderer', 'styles.css'), 'utf8'), /message\.user \{ justify-self: end/);
  assert.match(renderer, /id="approval-card"/);
  assert.match(renderer, /id="approval-status"/);
  assert.match(renderer, /approval-choice/);
  assert.match(fs.readFileSync(path.join(root, 'renderer', 'styles.css'), 'utf8'), /\.approval-card\[hidden\] \{ display: none/);
  assert.match(preload, /respondApproval:/);
  assert.match(main, /studio:respond-approval/);
  assert.match(main, /\/v1\/runs\/\$\{encodeURIComponent\(runId\)\}\/approval/);
  assert.match(fs.readFileSync(path.join(root, 'renderer', 'app.js'), 'utf8'), /Thinking…/);
  assert.match(fs.readFileSync(path.join(root, 'renderer', 'app.js'), 'utf8'), /payload\.output \|\| state\.output/);
  assert.match(fs.readFileSync(path.join(root, 'renderer', 'styles.css'), 'utf8'), /message\.assistant\.thinking/);
  assert.match(preload, /getSkin:/);
  assert.match(preload, /chooseSkinAsset:/);
  assert.match(main, /studio:choose-skin-asset/);
  assert.match(main, /importSkinAsset/);
  assert.match(fs.readFileSync(path.join(root, 'renderer', 'app.js'), 'utf8'), /saveCustomSkin/);
  assert.match(fs.readFileSync(path.join(root, 'renderer', 'styles.css'), 'utf8'), /midnight-garden/);
  assert.match(fs.readFileSync(path.join(root, 'renderer', 'app.js'), 'utf8'), /closeAccountDialog/);
});

test('Studio exposes real Hermes session history controls', () => {
  const rendererScript = fs.readFileSync(path.join(root, 'renderer', 'app.js'), 'utf8');
  assert.match(preload, /listSessions:/);
  assert.match(preload, /getSessionMessages:/);
  assert.match(preload, /deleteSession:/);
  assert.match(preload, /studio:delete-session/);
  assert.match(main, /method: 'DELETE'/);
  assert.match(main, /studio:list-sessions/);
  assert.match(main, /studio:get-session-messages/);
  assert.match(main, /无法连接 Hermes Studio 服务/);
  assert.match(main, /AbortSignal\.timeout\(5000\)/);
  assert.match(main, /async function accountLogin[\s\S]*?for \(let attempt = 0; attempt < 2/);
  assert.match(main, /ipcMain\.handle\('studio:login', async \(_event, input\) => \{/);
  assert.match(main, /return \{ ok: false, error: accountServiceError\(error\)\.message \};/);
  assert.match(rendererScript, /if \(!result\?\.ok\) throw new Error/);
  assert.match(main, /return \{ ok: false, error: accountServiceError\(error\)\.message \}/);
  assert.match(main, /studio:select-session/);
  assert.match(main, /newSessionTitle\(\)/);
  assert.match(main, /updateSessionTitle/);
  assert.match(main, /already in use/i);
  assert.match(rendererScript, /state\.activeSessionId = null/);
  assert.match(rendererScript, /messages\.replaceChildren\(\)/);
  assert.doesNotMatch(rendererScript, /if \(state\.activeSessionId === sessionId\) await startNewSession\(\)/);
  assert.match(rendererScript, /return message;/);
  assert.match(rendererScript, /state\.assistant\.article\.classList\.add\('thinking'\)/);
  assert.match(renderer, /id="model-select"/);
  assert.match(renderer, /gpt-5\.6-terra/);
  assert.match(renderer, /deepseek-v4-pro/);
  assert.match(renderer, /deepseek-v4-flash/);
  assert.doesNotMatch(renderer, /deepseek-chat/);
  assert.match(rendererScript, /modelSelect\.addEventListener\('change', \(\) => localStorage/);
  assert.doesNotMatch(rendererScript, /modelSelect\.addEventListener\('change', async/);
  assert.match(main, /Runtime identity: this conversation is running on provider/);
  assert.match(rendererScript, /hermes-studio-model/);
  assert.match(rendererScript, /runTask\(\{ prompt: displayTask, attachments, model \}\)/);
  assert.match(main, /allowedModels/);
  assert.match(main, /conversation_history: history, model/);
  assert.match(rendererScript, /prompt\.disabled = false/);
  assert.match(rendererScript, /applySkin\([\s\S]*?updateRunning\(false\)/);
  assert.match(renderer, /id="conversation-list"/);
  assert.match(renderer, /id="refresh-sessions"/);
  assert.match(rendererScript, /loadSessionMessages/);
  assert.match(rendererScript, /createDocumentFragment\(\)/);
  assert.match(rendererScript, /messages\.replaceChildren\(loaded\.fragment\)/);
  assert.match(rendererScript, /state\.loadingSession/);
  assert.match(rendererScript, /visibleHistoryEntries/);
  assert.match(rendererScript, /selected\.length >= 80/);
  assert.match(rendererScript, /totalCharacters \+ content\.length > 120000/);
  assert.match(rendererScript, /scrollTop = 0/);
  assert.match(rendererScript, /openSessionMenu/);
  assert.match(rendererScript, /deleteContextSession/);
  assert.match(rendererScript, /contextmenu/);
  assert.match(rendererScript, /refreshSessions/);
  assert.doesNotMatch(rendererScript, /formatSessionGroup|conversation-group-label/);
  assert.match(renderer, /<p class="eyebrow">历史对话<\/p>/);
});
